# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ldevy <ldevy@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/22 17:34:16 by ldevy             #+#    #+#              #
#    Updated: 2023/02/16 18:54:30 by ldevy            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME 	= poly

RM		= rm -rf

CC		= c++

SRCS	= main.cpp $(addprefix srcs/, Bureaucrate.cpp) #WrongAnimal.cpp WrongCat.cpp

INC		= $(addprefix includes/, includes.hpp Bureaucrate.hpp) #WrongAnimal.hpp WrongCat.hpp

OBJS	= $(SRCS:%.cpp=%.o)

CFLAGS	= -Wall -Wextra -Werror -std=c++98 -I includes -g3

all:		${NAME}

${NAME}: ${OBJS} ${INC}
	${CC} ${CFLAGS} ${OBJS} -o ${NAME} 

.cpp.o:
	${CC} ${CFLAGS} -c $< -o $(<:.cpp=.o)

clean: 
	${RM} ${OBJS}
fclean: clean		
	${RM} ${NAME}

re:		fclean all

.PHONY: all fclean clean re 
